### ISSUE TITLE
Add note of development status

### ISSUE THREAD

**Issue by Ein-Tim** [CoraLibre/CoraLibre-website#4]
According to https://github.com/CoraLibre/CoraLibre-android-sdk#note-on-development-status the development on this project is stalled. 
Instead you refer to [CCTG](https://codeberg.org/corona-contact-tracing-germany/cwa-android). 

If there are no plans to continue the development in the near future, a note should be added to https://coralibre.de/, saying something like:

"Die CoraLibre App wird momentan nicht weiterentwickelt. Das bedeutet, dass Features & Verbesserungen, die in neueren Versionen der Corona-Warn-App vorgenommen wurden, nicht in der CoraLibre App enthalten sind."

The translated text should be shown on the English page.

If you want to you can also refer to CCTG.

**Comment by 1Maxnet1** [comment]
Additionally I would remove the apk to download it, so it does not get used anymore.

**Comment by Ein-Tim** [comment]
https://coralibre.de/ does not exist anymore.

Closing this issue.
